export const ADVERT_LIST_REQUEST = "ADVERT_LIST_REQUEST";
export const ADVERT_LIST_SUCCESS = "ADVERT_LIST_SUCCESS";
export const ADVERT_LIST_FAIL = "ADVERT_LIST_FAIL";

export const UPLOAD_ADVERT_REQUEST = "UPLOAD_ADVERT_REQUEST";
export const UPLOAD_ADVERT_SUCCESS = "UPLOAD_ADVERT_SUCCESS";
export const UPLOAD_ADVERT_FAIL = "UPLOAD_ADVERT_FAIL";
export const UPLOAD_ADVERT_RESET = "UPLOAD_ADVERT_RESET";

export const ADVERT_DETAILS_REQUEST = "ADVERT_DETAILS_REQUEST";
export const ADVERT_DETAILS_SUCCESS = "ADVERT_DETAILS_SUCCESS";
export const ADVERT_DETAILS_FAIL = "ADVERT_DETAILS_FAIL";

export const ADVERT_PARAMS_REQUEST = "ADVERT_PARAMS_REQUEST";
export const ADVERT_PARAMS_SUCCESS = "ADVERT_PARAMS_SUCCESS";
export const ADVERT_PARAMS_FAIL = "ADVERT_PARAMS_FAIL";

export const ADVERT_UPDATE_REQUEST = "ADVERT_UPDATE_REQUEST";
export const ADVERT_UPDATE_SUCCESS = "ADVERT_UPDATE_SUCCESS";
export const ADVERT_UPDATE_FAIL = "ADVERT_UPDATE_FAIL";
export const ADVERT_UPDATE_RESET = "ADVERT_UPDATE_RESET";

export const ADVERT_DELETE_REQUEST = "ADVERT_DELETE_REQUEST";
export const ADVERT_DELETE_SUCCESS = "ADVERT_DELETE_SUCCESS";
export const ADVERT_DELETE_FAIL = "ADVERT_DELETE_FAIL";
export const ADVERT_DELETE_RESET = "ADVERT_DELETE_RESET";

export const LIKE_ADVERT_REQUEST = "LIKE_ADVERT_REQUEST";
export const LIKE_ADVERT_SUCCESS = "LIKE_ADVERT_SUCCESS";
export const LIKE_ADVERT_FAIL = "LIKE_ADVERT_FAIL";

export const UNLIKE_ADVERT_REQUEST = "UNLIKE_ADVERT_REQUEST";
export const UNLIKE_ADVERT_SUCCESS = "UNLIKE_ADVERT_SUCCESS";
export const UNLIKE_ADVERT_FAIL = "UNLIKE_ADVERT_FAIL";

export const ADVERT_FLAG_REQUEST = "ADVERT_FLAG_REQUEST";
export const ADVERT_FLAG_SUCCESS = "ADVERT_FLAG_SUCCESS";
export const ADVERT_FLAG_FAIL = "ADVERT_FLAG_FAIL";

export const REVIEW_ADVERT_REQUEST = "REVIEW_ADVERT_REQUEST";
export const REVIEW_ADVERT_SUCCESS = "REVIEW_ADVERT_SUCCESS";
export const REVIEW_ADVERT_FAIL = "REVIEW_ADVERT_FAIL";
export const REVIEW_ADVERT_RESET = "REVIEW_ADVERT_RESET";
