export const SCREEN_CALENDAR_REQUEST = "SCREEN_CALENDAR_REQUEST";
export const SCREEN_CALENDAR_SUCCESS = "SCREEN_CALENDAR_SUCCESS";
export const SCREEN_CALENDAR_FAIL = "SCREEN_CALENDAR_FAIL";

export const ADD_CALENDAR_DATA_REQUEST = "ADD_CALENDAR_DATA_REQUEST";
export const ADD_CALENDAR_DATA_SUCCESS = "ADD_CALENDAR_DATA_SUCCESS";
export const ADD_CALENDAR_DATA_FAIL = "ADD_CALENDAR_DATA_FAIL";

export const BOOK_DAY_SLOT_REQUEST = "BOOK_DAY_SLOT_REQUEST";
export const BOOK_DAY_SLOT_SUCCESS = "BOOK_DAY_SLOT_SUCCESS";
export const BOOK_DAY_SLOT_FAIL = "BOOK_DAY_SLOT_FAIL";

export const BOOK_SLOT_REQUEST = "BOOK_SLOT_REQUEST";
export const BOOK_SLOT_SUCCESS = "BOOK_SLOT_SUCCESS";
export const BOOK_SLOT_FAIL = "BOOK_SLOT_FAIL";

export const BOOK_DAY_REQUEST = "BOOK_DAY_REQUEST";
export const BOOK_DAY_SUCCESS = "BOOK_DAY_SUCCESS";
export const BOOK_DAY_FAIL = "BOOK_DAY_FAIL";
