export const DETAILS_SCREEN_GAME_REQUEST = "DETAILS_SCREEN_GAME_REQUEST";
export const DETAILS_SCREEN_GAME_SUCCESS = "DETAILS_SCREEN_GAME_SUCCESS";
export const DETAILS_SCREEN_GAME_FAIL = "DETAILS_SCREEN_GAME_FAIL";

export const CREATE_SCREEN_GAME_REQUEST = "CREATE_SCREEN_GAME_REQUEST";
export const CREATE_SCREEN_GAME_SUCCESS = "CREATE_SCREEN_GAME_SUCCESS";
export const CREATE_SCREEN_GAME_FAIL = "CREATE_SCREEN_GAME_FAIL";

export const REMOVE_SCREEN_GAME_REQUEST = "REMOVE_SCREEN_GAME_REQUEST";
export const REMOVE_SCREEN_GAME_SUCCESS = "REMOVE_SCREEN_GAME_SUCCESS";
export const REMOVE_SCREEN_GAME_FAIL = "REMOVE_SCREEN_GAME_SUCCESS";

export const DETAILS_ADVERT_GAME_REQUEST = "DETAILS_ADVERT_GAME_REQUEST";
export const DETAILS_ADVERT_GAME_SUCCESS = "DETAILS_ADVERT_GAME_SUCCESS";
export const DETAILS_ADVERT_GAME_FAIL = "DETAILS_ADVERT_GAME_FAIL";

export const CREATE_ADVERT_GAME_REQUEST = "CREATE_ADVERT_GAME_REQUEST";
export const CREATE_ADVERT_GAME_SUCCESS = "CREATE_ADVERT_GAME_SUCCESS";
export const CREATE_ADVERT_GAME_FAIL = "CREATE_ADVERT_GAME_FAIL";

export const REMOVE_ADVERT_GAME_REQUEST = "REMOVE_ADVERT_GAME_REQUEST";
export const REMOVE_ADVERT_GAME_SUCCESS = "REMOVE_ADVERT_GAME_SUCCESS";
export const REMOVE_ADVERT_GAME_FAIL = "REMOVE_ADVERT_GAME_SUCCESS";
