export const MEDIA_UPLOAD_REQUEST = "MEDIA_UPLOAD_REQUEST";
export const MEDIA_UPLOAD_SUCCESS = "MEDIA_UPLOAD_SUCCESS";
export const MEDIA_UPLOAD_FAIL = "MEDIA_UPLOAD_FAIL";
export const MEDIA_UPLOAD_RESET = "MEDIA_UPLOAD_RESET";

export const GET_MEDIA_REQUEST = "GET_MEDIA_REQUEST";
export const GET_MEDIA_SUCCESS = "GET_MEDIA_SUCCESS";
export const GET_MEDIA_FAIL = "GET_MEDIA_FAIL";

export const GET_ALL_MEDIA_REQUEST = "GET_ALL_MEDIA_REQUEST";
export const GET_ALL_MEDIA_SUCCESS = "GET_ALL_MEDIA_SUCCESS";
export const GET_ALL_MEDIA_FAIL = "GET_ALL_MEDIA_FAIL";

export const GET_MY_MEDIA_REQUEST = "GET_MY_MEDIA_REQUEST";
export const GET_MY_MEDIA_SUCCESS = "GET_MY_MEDIA_SUCCESS";
export const GET_MY_MEDIA_FAIL = "GET_MY_MEDIA_FAIL";

export const GENERATE_VIDEO_FROM_IMAGES_REQUEST =
  "GENERATE_VIDEO_FROM_IMAGES_REQUEST";
export const GENERATE_VIDEO_FROM_IMAGES_SUCCESS =
  "GENERATE_VIDEO_FROM_IMAGES_SUCCESS";
export const GENERATE_VIDEO_FROM_IMAGES_FAIL =
  "GENERATE_VIDEO_FROM_IMAGES_FAIL";
