export const ALL_PINS_GET_REQUEST = "ALL_PINS_GET_REQUEST";
export const ALL_PINS_GET_SUCCESS = "ALL_PINS_GET_SUCCESS";
export const ALL_PINS_GET_FAIL = "ALL_PINS_GET_FAIL";

export const PIN_GET_REQUEST = "PIN_GET_REQUEST";
export const PIN_GET_SUCCESS = "PIN_GET_SUCCESS";
export const PIN_GET_FAIL = "PIN_GET_FAIL";

export const PIN_UPDATE_REQUEST = "PIN_UPDATE_REQUEST";
export const PIN_UPDATE_SUCCESS = "PIN_UPDATE_SUCCESS";
export const PIN_UPDATE_FAIL = "PIN_UPDATE_FAIL";
export const PIN_UPDATE_RESET = "PIN_UPDATE_RESET";
